### ISSUE TITLE
如何对树进行增删改？

### ISSUE THREAD

**Issue by songispm** [07akioni/treemate#128]
我看文档里对在节点中移动有提及，但说的也不是很清楚，麻烦可以详细说下吗？

以及是否可以通过实例，直接从某个具体节点下，增加节点，删除节点，修改节点数据

**Comment by 07akioni** [comment]
增删改只能通过改变树的源头来做，treemate 的数据是 immutable 的

**Comment by 07akioni** [comment]
也就是说改变传入的 data，treemate 是对一个静态的树提供一些对应的功能

**Comment by songispm** [comment]
那我自己改变了数据，还得再次重新 createTreeMate(全新的一整份树型数据)，是吧？
这好麻烦啊

**Comment by 07akioni** [comment]
> 那我自己改变了数据，还得再次重新 createTreeMate(全新的一整份树型数据)，是吧？ 这好麻烦啊

是的，这个库就是这么设计的
